-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  account_code text NOT NULL,
  account_name text NOT NULL,
  account_type text NOT NULL CHECK (account_type = ANY (ARRAY['asset'::text, 'liability'::text, 'equity'::text, 'income'::text, 'expense'::text])),
  parent_account_id uuid,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  is_system boolean NOT NULL DEFAULT false,
  normal_balance text NOT NULL DEFAULT 'debit'::text CHECK (normal_balance = ANY (ARRAY['debit'::text, 'credit'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cost_category text CHECK (cost_category = ANY (ARRAY['programme'::text, 'admin'::text, 'fundraising'::text, 'other'::text])),
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT accounts_parent_account_id_fkey FOREIGN KEY (parent_account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.amanah_index_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  score_version text NOT NULL DEFAULT 'amanah_v1'::text,
  score_value numeric NOT NULL CHECK (score_value >= 0::numeric AND score_value <= 100::numeric),
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  computed_from_event_id uuid,
  breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  public_summary text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT amanah_index_history_pkey PRIMARY KEY (id),
  CONSTRAINT amanah_index_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT amanah_index_history_computed_from_event_id_fkey FOREIGN KEY (computed_from_event_id) REFERENCES public.trust_events(id)
);
CREATE TABLE public.app_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_key text NOT NULL UNIQUE,
  app_name text NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::app_catalog_status,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_catalog_pkey PRIMARY KEY (id)
);
CREATE TABLE public.app_installations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  app_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'enabled'::app_installation_status,
  installed_by_user_id uuid,
  installed_at timestamp with time zone NOT NULL DEFAULT now(),
  disabled_at timestamp with time zone,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT app_installations_pkey PRIMARY KEY (id),
  CONSTRAINT app_installations_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.app_catalog(id),
  CONSTRAINT app_installations_installed_by_user_id_fkey FOREIGN KEY (installed_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT app_installations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_user_id uuid,
  actor_role text,
  organization_id uuid,
  action text NOT NULL,
  entity_table text,
  entity_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  account_name text NOT NULL,
  bank_name text,
  account_number text,
  account_type text NOT NULL DEFAULT 'bank'::text CHECK (account_type = ANY (ARRAY['bank'::text, 'cash'::text, 'e_wallet'::text, 'payment_gateway'::text])),
  fund_type text CHECK (fund_type = ANY (ARRAY['zakat'::text, 'waqf'::text, 'sadaqah'::text, 'general'::text, 'mixed'::text])),
  linked_account_id uuid,
  currency text NOT NULL DEFAULT 'MYR'::text,
  is_active boolean NOT NULL DEFAULT true,
  is_primary boolean NOT NULL DEFAULT false,
  opening_balance numeric NOT NULL DEFAULT 0,
  opening_balance_date date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT bank_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT bank_accounts_linked_account_id_fkey FOREIGN KEY (linked_account_id) REFERENCES public.accounts(id)
);
CREATE TABLE public.bank_reconciliations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  bank_account_id uuid NOT NULL,
  period_year integer NOT NULL,
  period_month integer NOT NULL CHECK (period_month >= 1 AND period_month <= 12),
  statement_date date NOT NULL,
  statement_ending_balance numeric NOT NULL,
  book_balance numeric,
  difference numeric DEFAULT (statement_ending_balance - COALESCE(book_balance, (0)::numeric)),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'reconciled'::text, 'discrepancy'::text])),
  reconciled_at timestamp with time zone,
  reconciled_by_user_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id),
  CONSTRAINT bank_reconciliations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT bank_reconciliations_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT bank_reconciliations_reconciled_by_user_id_fkey FOREIGN KEY (reconciled_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.billing_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_key text NOT NULL UNIQUE,
  plan_name text NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::billing_plan_status,
  monthly_amount numeric NOT NULL DEFAULT 0,
  yearly_amount numeric NOT NULL DEFAULT 0,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.certification_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'under_review'::text, 'approved'::text, 'rejected'::text])),
  submitted_at timestamp with time zone,
  submitted_by_user_id uuid,
  reviewer_assigned_user_id uuid,
  reviewer_comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT certification_applications_pkey PRIMARY KEY (id),
  CONSTRAINT certification_applications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT certification_applications_submitted_by_user_id_fkey FOREIGN KEY (submitted_by_user_id) REFERENCES public.users(id),
  CONSTRAINT certification_applications_reviewer_assigned_user_id_fkey FOREIGN KEY (reviewer_assigned_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.certification_evaluations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  certification_application_id uuid,
  criteria_version text NOT NULL DEFAULT 'ctcf_v1'::text,
  total_score numeric NOT NULL CHECK (total_score >= 0::numeric AND total_score <= 100::numeric),
  score_breakdown jsonb NOT NULL DEFAULT '{}'::jsonb,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  computed_by_user_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT certification_evaluations_pkey PRIMARY KEY (id),
  CONSTRAINT certification_evaluations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT certification_evaluations_certification_application_id_fkey FOREIGN KEY (certification_application_id) REFERENCES public.certification_applications(id),
  CONSTRAINT certification_evaluations_computed_by_user_id_fkey FOREIGN KEY (computed_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.certification_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  certification_application_id uuid,
  evaluation_id uuid,
  previous_status text,
  new_status text NOT NULL CHECK (new_status = ANY (ARRAY['certified'::text, 'not_certified'::text, 'suspended'::text])),
  valid_from date,
  valid_to date,
  decided_by_user_id uuid NOT NULL,
  decision_reason text,
  decided_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT certification_history_pkey PRIMARY KEY (id),
  CONSTRAINT certification_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT certification_history_certification_application_id_fkey FOREIGN KEY (certification_application_id) REFERENCES public.certification_applications(id),
  CONSTRAINT certification_history_evaluation_id_fkey FOREIGN KEY (evaluation_id) REFERENCES public.certification_evaluations(id),
  CONSTRAINT certification_history_decided_by_user_id_fkey FOREIGN KEY (decided_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.donation_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  project_id uuid,
  donor_user_id uuid,
  donor_email text,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  platform_fee_amount numeric NOT NULL DEFAULT 0 CHECK (platform_fee_amount >= 0::numeric),
  currency text NOT NULL DEFAULT 'MYR'::text,
  status text NOT NULL DEFAULT 'initiated'::text CHECK (status = ANY (ARRAY['initiated'::text, 'pending'::text, 'confirmed'::text, 'failed'::text, 'canceled'::text])),
  gateway text NOT NULL CHECK (gateway = ANY (ARRAY['toyyibpay'::text, 'billplz'::text])),
  gateway_checkout_id text,
  gateway_transaction_id text,
  initiated_at timestamp with time zone NOT NULL DEFAULT now(),
  confirmed_at timestamp with time zone,
  failure_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT donation_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT donation_transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT donation_transactions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT donation_transactions_donor_user_id_fkey FOREIGN KEY (donor_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.evidence_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  project_report_id uuid NOT NULL,
  file_name text NOT NULL,
  mime_type text NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'evidence'::text,
  storage_path text NOT NULL,
  file_size_bytes bigint,
  sha256 text,
  captured_at timestamp with time zone,
  geo_lat numeric,
  geo_lng numeric,
  visibility text NOT NULL DEFAULT 'private'::text CHECK (visibility = ANY (ARRAY['private'::text, 'reviewer_only'::text, 'public'::text])),
  is_approved_public boolean NOT NULL DEFAULT false,
  approved_by_user_id uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT evidence_files_pkey PRIMARY KEY (id),
  CONSTRAINT evidence_files_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT evidence_files_project_report_id_fkey FOREIGN KEY (project_report_id) REFERENCES public.project_reports(id),
  CONSTRAINT evidence_files_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.financial_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  period_year integer NOT NULL,
  currency text NOT NULL DEFAULT 'MYR'::text,
  inputs jsonb NOT NULL DEFAULT '{}'::jsonb,
  submission_status text NOT NULL DEFAULT 'draft'::text CHECK (submission_status = ANY (ARRAY['draft'::text, 'submitted'::text])),
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'changes_requested'::text, 'rejected'::text])),
  submitted_at timestamp with time zone,
  verified_at timestamp with time zone,
  verified_by_user_id uuid,
  reviewer_comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT financial_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT financial_snapshots_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT financial_snapshots_verified_by_user_id_fkey FOREIGN KEY (verified_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.fund_period_closes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  period_year integer NOT NULL,
  period_month integer,
  closed_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_by_user_id uuid,
  total_income numeric NOT NULL DEFAULT 0,
  total_expense numeric NOT NULL DEFAULT 0,
  net_movement numeric DEFAULT (total_income - total_expense),
  fund_balances jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  financial_snapshot_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fund_period_closes_pkey PRIMARY KEY (id),
  CONSTRAINT fund_period_closes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT fund_period_closes_closed_by_user_id_fkey FOREIGN KEY (closed_by_user_id) REFERENCES public.users(id),
  CONSTRAINT fund_period_closes_financial_snapshot_id_fkey FOREIGN KEY (financial_snapshot_id) REFERENCES public.financial_snapshots(id)
);
CREATE TABLE public.funds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  fund_code text NOT NULL,
  fund_name text NOT NULL,
  fund_type text NOT NULL CHECK (fund_type = ANY (ARRAY['zakat'::text, 'waqf'::text, 'sadaqah'::text, 'general'::text, 'project'::text, 'endowment'::text])),
  restriction_level text NOT NULL DEFAULT 'unrestricted'::text CHECK (restriction_level = ANY (ARRAY['unrestricted'::text, 'temporarily_restricted'::text, 'permanently_restricted'::text])),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  is_system boolean NOT NULL DEFAULT false,
  currency text NOT NULL DEFAULT 'MYR'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT funds_pkey PRIMARY KEY (id),
  CONSTRAINT funds_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.governance_case_action_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  finding_id uuid,
  title text NOT NULL,
  description text,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'submitted'::text, 'verified'::text, 'rejected'::text, 'cancelled'::text])),
  assigned_role_label text,
  owner_name text,
  due_at timestamp with time zone,
  resolution_note text,
  created_by_user_id uuid,
  verified_by_user_id uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_action_items_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_action_items_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id),
  CONSTRAINT governance_case_action_items_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.governance_case_findings(id)
);
CREATE TABLE public.governance_case_action_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  action_item_id uuid NOT NULL,
  source text NOT NULL DEFAULT 'amanah_os'::text CHECK (source = ANY (ARRAY['console'::text, 'amanah_os'::text])),
  update_type text NOT NULL DEFAULT 'resubmission'::text CHECK (update_type = ANY (ARRAY['note'::text, 'evidence_submitted'::text, 'status_update'::text, 'resubmission'::text])),
  message text NOT NULL,
  proposed_status text CHECK (proposed_status IS NULL OR (proposed_status = ANY (ARRAY['open'::text, 'in_progress'::text, 'submitted'::text, 'verified'::text, 'rejected'::text, 'cancelled'::text]))),
  attachment_url text,
  submitted_by_user_id uuid,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  review_status text NOT NULL DEFAULT 'pending'::text CHECK (review_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'needs_more_info'::text])),
  review_note text,
  reviewed_by_user_id uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_action_updates_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_action_updates_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id),
  CONSTRAINT governance_case_action_updates_action_item_id_fkey FOREIGN KEY (action_item_id) REFERENCES public.governance_case_action_items(id)
);
CREATE TABLE public.governance_case_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  assignee_user_id uuid NOT NULL,
  assignment_role text NOT NULL CHECK (assignment_role = ANY (ARRAY['reviewer'::text, 'scholar'::text, 'approver'::text])),
  status text NOT NULL DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'accepted'::text, 'completed'::text, 'removed'::text])),
  notes text,
  assigned_by_user_id uuid,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  responded_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_assignments_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id)
);
CREATE TABLE public.governance_case_clarifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  target_kind text NOT NULL CHECK (target_kind = ANY (ARRAY['case'::text, 'finding'::text, 'evidence'::text, 'action_item'::text])),
  finding_id uuid,
  evidence_id uuid,
  action_item_id uuid,
  submitted_by_user_id uuid,
  submitted_by_role text CHECK (submitted_by_role = ANY (ARRAY['organization_admin'::text, 'organization_reviewer'::text, 'organization_finance'::text, 'organization_staff'::text, 'system'::text])),
  title text NOT NULL,
  response_text text NOT NULL,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['submitted'::text, 'under_review'::text, 'accepted'::text, 'needs_more_info'::text, 'rejected'::text])),
  review_note text,
  reviewed_at timestamp with time zone,
  reviewed_by_user_id uuid,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_clarifications_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_clarifications_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id),
  CONSTRAINT governance_case_clarifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT governance_case_clarifications_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.governance_case_findings(id),
  CONSTRAINT governance_case_clarifications_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.governance_case_evidence(id),
  CONSTRAINT governance_case_clarifications_action_item_id_fkey FOREIGN KEY (action_item_id) REFERENCES public.governance_case_action_items(id),
  CONSTRAINT governance_case_clarifications_submitted_by_user_id_fkey FOREIGN KEY (submitted_by_user_id) REFERENCES public.users(id),
  CONSTRAINT governance_case_clarifications_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.governance_case_decisions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  decision_stage text NOT NULL CHECK (decision_stage = ANY (ARRAY['reviewer'::text, 'scholar'::text, 'approver'::text])),
  decision text NOT NULL CHECK (decision = ANY (ARRAY['advance_to_scholar'::text, 'advance_to_approval'::text, 'approve'::text, 'approve_conditional'::text, 'improvement_required'::text, 'reject'::text, 'expire'::text])),
  result_status text NOT NULL CHECK (result_status = ANY (ARRAY['under_review'::text, 'scholar_review'::text, 'approval_pending'::text, 'approved'::text, 'improvement_required'::text, 'rejected'::text, 'expired'::text])),
  result_outcome text CHECK (result_outcome IS NULL OR (result_outcome = ANY (ARRAY['approved'::text, 'conditional'::text, 'improvement_required'::text, 'rejected'::text, 'expired'::text]))),
  decision_note text,
  conditions_text text,
  decided_by_user_id uuid,
  decided_at timestamp with time zone NOT NULL DEFAULT now(),
  emitted_trust_event_type text,
  emitted_trust_event_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_decisions_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_decisions_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id)
);
CREATE TABLE public.governance_case_evidence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  finding_id uuid,
  evidence_type text NOT NULL DEFAULT 'note'::text CHECK (evidence_type = ANY (ARRAY['note'::text, 'link'::text, 'document'::text, 'snapshot'::text])),
  title text NOT NULL,
  evidence_url text,
  notes text,
  recorded_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_evidence_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id),
  CONSTRAINT governance_case_evidence_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.governance_case_findings(id)
);
CREATE TABLE public.governance_case_findings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  finding_type text NOT NULL DEFAULT 'governance'::text CHECK (finding_type = ANY (ARRAY['governance'::text, 'finance'::text, 'shariah'::text, 'operations'::text, 'documentation'::text, 'risk'::text])),
  severity text NOT NULL DEFAULT 'minor'::text CHECK (severity = ANY (ARRAY['info'::text, 'minor'::text, 'major'::text, 'critical'::text])),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'accepted'::text, 'resolved'::text, 'waived'::text])),
  title text NOT NULL,
  details text,
  recommendation text,
  recorded_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_findings_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_findings_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id)
);
CREATE TABLE public.governance_case_recommendations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL,
  assignment_id uuid,
  submitted_by_user_id uuid NOT NULL,
  recommendation text NOT NULL CHECK (recommendation = ANY (ARRAY['approve'::text, 'approve_with_conditions'::text, 'remediate'::text, 'reject'::text, 'escalate'::text, 'info_required'::text])),
  summary text NOT NULL,
  detailed_notes text,
  status text NOT NULL DEFAULT 'submitted'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'superseded'::text])),
  submitted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_case_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT governance_case_recommendations_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.governance_case_assignments(id),
  CONSTRAINT governance_case_recommendations_submitted_by_user_id_fkey FOREIGN KEY (submitted_by_user_id) REFERENCES public.users(id),
  CONSTRAINT governance_case_recommendations_case_id_fkey FOREIGN KEY (case_id) REFERENCES public.governance_review_cases(id)
);
CREATE TABLE public.governance_event_intake (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trust_event_id uuid NOT NULL UNIQUE,
  organization_id uuid NOT NULL,
  event_type text NOT NULL,
  pillar text,
  source text NOT NULL,
  event_ref_table text,
  event_ref_id uuid,
  occurred_at timestamp with time zone NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  routing_mode text NOT NULL CHECK (routing_mode = ANY (ARRAY['open_case'::text, 'update_case'::text])),
  suggested_case_type text NOT NULL CHECK (suggested_case_type = ANY (ARRAY['onboarding_review'::text, 'periodic_review'::text, 'corrective_review'::text, 'renewal_review'::text])),
  suggested_priority text NOT NULL CHECK (suggested_priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  suggested_assignment_role text NOT NULL CHECK (suggested_assignment_role = ANY (ARRAY['reviewer'::text, 'scholar'::text, 'approver'::text])),
  intake_status text NOT NULL DEFAULT 'pending'::text CHECK (intake_status = ANY (ARRAY['pending'::text, 'ignored'::text, 'case_opened'::text, 'case_updated'::text, 'error'::text])),
  linked_case_id uuid,
  handler_note text,
  handled_by_user_id uuid,
  handled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_event_intake_pkey PRIMARY KEY (id),
  CONSTRAINT governance_event_intake_trust_event_id_fkey FOREIGN KEY (trust_event_id) REFERENCES public.trust_events(id),
  CONSTRAINT governance_event_intake_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT governance_event_intake_linked_case_id_fkey FOREIGN KEY (linked_case_id) REFERENCES public.governance_review_cases(id)
);
CREATE TABLE public.governance_event_rules (
  event_type text NOT NULL,
  routing_mode text NOT NULL CHECK (routing_mode = ANY (ARRAY['open_case'::text, 'update_case'::text])),
  default_case_type text NOT NULL CHECK (default_case_type = ANY (ARRAY['onboarding_review'::text, 'periodic_review'::text, 'corrective_review'::text, 'renewal_review'::text])),
  default_priority text NOT NULL CHECK (default_priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  default_assignment_role text NOT NULL CHECK (default_assignment_role = ANY (ARRAY['reviewer'::text, 'scholar'::text, 'approver'::text])),
  title text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT governance_event_rules_pkey PRIMARY KEY (event_type)
);
CREATE TABLE public.governance_review_cases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_code text NOT NULL UNIQUE,
  organization_id uuid NOT NULL,
  review_type text NOT NULL DEFAULT 'governance_review'::text CHECK (review_type = ANY (ARRAY['governance_review'::text, 'onboarding_review'::text, 'periodic_review'::text, 'renewal_review'::text, 'corrective_review'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'under_review'::text, 'scholar_review'::text, 'approval_pending'::text, 'approved'::text, 'improvement_required'::text, 'rejected'::text, 'expired'::text])),
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  intake_source text NOT NULL DEFAULT 'console'::text,
  summary text,
  due_at timestamp with time zone,
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_at timestamp with time zone,
  review_started_at timestamp with time zone,
  scholar_started_at timestamp with time zone,
  approval_started_at timestamp with time zone,
  closed_at timestamp with time zone,
  outcome text CHECK (outcome IS NULL OR (outcome = ANY (ARRAY['approved'::text, 'conditional'::text, 'improvement_required'::text, 'rejected'::text, 'expired'::text]))),
  created_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source_event_id uuid,
  CONSTRAINT governance_review_cases_pkey PRIMARY KEY (id),
  CONSTRAINT governance_review_cases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT governance_review_cases_source_event_id_fkey FOREIGN KEY (source_event_id) REFERENCES public.trust_events(id)
);
CREATE TABLE public.journal_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  entry_date date NOT NULL,
  reference_no text,
  description text NOT NULL,
  entry_type text NOT NULL DEFAULT 'manual'::text CHECK (entry_type = ANY (ARRAY['manual'::text, 'donation'::text, 'fund_transfer'::text, 'period_close'::text, 'adjustment'::text])),
  source_id uuid,
  period_year integer NOT NULL,
  period_month integer CHECK (period_month >= 1 AND period_month <= 12),
  is_locked boolean NOT NULL DEFAULT false,
  locked_at timestamp with time zone,
  locked_by_user_id uuid,
  created_by_user_id uuid,
  approved_by_user_id uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT journal_entries_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT journal_entries_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id),
  CONSTRAINT journal_entries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT journal_entries_locked_by_user_id_fkey FOREIGN KEY (locked_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.journal_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  journal_entry_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  account_id uuid NOT NULL,
  fund_id uuid NOT NULL,
  project_id uuid,
  debit_amount numeric NOT NULL DEFAULT 0 CHECK (debit_amount >= 0::numeric),
  credit_amount numeric NOT NULL DEFAULT 0 CHECK (credit_amount >= 0::numeric),
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT journal_lines_pkey PRIMARY KEY (id),
  CONSTRAINT journal_lines_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id),
  CONSTRAINT journal_lines_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT journal_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT journal_lines_fund_id_fkey FOREIGN KEY (fund_id) REFERENCES public.funds(id),
  CONSTRAINT journal_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.org_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  uploaded_by_user_id uuid,
  document_category text NOT NULL,
  document_type text NOT NULL,
  label text NOT NULL,
  description text,
  file_name text NOT NULL,
  mime_type text,
  storage_bucket text NOT NULL DEFAULT 'documents'::text,
  storage_path text NOT NULL,
  file_size_bytes integer,
  sha256 text,
  period_year integer,
  visibility text NOT NULL DEFAULT 'private'::text CHECK (visibility = ANY (ARRAY['private'::text, 'public'::text])),
  is_approved_public boolean NOT NULL DEFAULT false,
  approved_by_user_id uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_documents_pkey PRIMARY KEY (id),
  CONSTRAINT org_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT org_documents_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.users(id),
  CONSTRAINT org_documents_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.org_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  invited_email text NOT NULL,
  org_role text NOT NULL CHECK (org_role = ANY (ARRAY['org_admin'::text, 'org_manager'::text, 'org_viewer'::text])),
  invited_by_user_id uuid NOT NULL,
  token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'revoked'::text])),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT org_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT org_invitations_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.org_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  org_role text NOT NULL CHECK (org_role = ANY (ARRAY['org_admin'::text, 'org_manager'::text, 'org_viewer'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'removed'::text])),
  invited_by_user_id uuid,
  invited_at timestamp with time zone,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_members_pkey PRIMARY KEY (id),
  CONSTRAINT org_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT org_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT org_members_invited_by_user_id_fkey FOREIGN KEY (invited_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_billing_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  subscription_id uuid,
  invoice_ref text NOT NULL,
  billing_period_label text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  currency_code text NOT NULL DEFAULT 'MYR'::text CHECK (char_length(currency_code) = 3),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'issued'::text, 'paid'::text, 'void'::text])),
  billed_at timestamp with time zone NOT NULL DEFAULT now(),
  paid_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_billing_records_pkey PRIMARY KEY (id),
  CONSTRAINT organization_billing_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_billing_records_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.organization_subscriptions(id)
);
CREATE TABLE public.organization_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  plan_id uuid NOT NULL,
  billing_cycle text NOT NULL DEFAULT 'monthly'::text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'past_due'::text, 'cancelled'::text])),
  amount numeric NOT NULL DEFAULT 0,
  currency_code text NOT NULL DEFAULT 'MYR'::text CHECK (char_length(currency_code) = 3),
  seats_included integer NOT NULL DEFAULT 1,
  seats_used integer NOT NULL DEFAULT 0,
  starts_at timestamp with time zone NOT NULL DEFAULT now(),
  next_billing_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT organization_subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.billing_plans(id)
);
CREATE TABLE public.organization_trust_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  source_case_id uuid,
  snapshot_status text NOT NULL DEFAULT 'draft'::text CHECK (snapshot_status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  trust_level text NOT NULL DEFAULT 'developing'::text CHECK (trust_level = ANY (ARRAY['unrated'::text, 'watchlist'::text, 'developing'::text, 'assured'::text, 'exemplary'::text])),
  verification_badge text NOT NULL DEFAULT 'reviewed'::text CHECK (verification_badge = ANY (ARRAY['none'::text, 'reviewed'::text, 'scholar_reviewed'::text, 'approved'::text])),
  governance_status text NOT NULL DEFAULT 'under_review'::text CHECK (governance_status = ANY (ARRAY['under_review'::text, 'improvement_required'::text, 'approved'::text, 'approved_conditional'::text, 'rejected'::text, 'suspended'::text])),
  public_summary text NOT NULL,
  public_highlights jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(public_highlights) = 'array'::text),
  internal_note text,
  effective_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  published_by_user_id uuid,
  created_by_user_id uuid,
  is_current boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_trust_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT organization_trust_snapshots_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_trust_snapshots_source_case_id_fkey FOREIGN KEY (source_case_id) REFERENCES public.governance_review_cases(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  legal_name text,
  registration_no text,
  website_url text,
  contact_email text,
  contact_phone text,
  address_text text,
  country text NOT NULL DEFAULT 'MY'::text,
  state text,
  org_type text CHECK (org_type = ANY (ARRAY['ngo'::text, 'mosque_surau'::text, 'waqf_institution'::text, 'zakat_body'::text, 'foundation'::text, 'cooperative'::text, 'other'::text])),
  oversight_authority text,
  fund_types ARRAY,
  summary text,
  onboarding_status text NOT NULL DEFAULT 'draft'::text CHECK (onboarding_status = ANY (ARRAY['draft'::text, 'submitted'::text, 'changes_requested'::text, 'approved'::text, 'rejected'::text])),
  listing_status text NOT NULL DEFAULT 'private'::text CHECK (listing_status = ANY (ARRAY['private'::text, 'listed'::text, 'unlisted'::text, 'suspended'::text])),
  onboarding_submitted_at timestamp with time zone,
  approved_at timestamp with time zone,
  approved_by_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  workspace_status text NOT NULL DEFAULT 'draft'::text CHECK (workspace_status = ANY (ARRAY['draft'::text, 'active'::text, 'suspended'::text, 'archived'::text])),
  owner_user_id uuid,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id),
  CONSTRAINT organizations_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  request_no text NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  fund_id uuid NOT NULL,
  expense_account_id uuid,
  bank_account_id uuid,
  project_id uuid,
  payment_date date,
  vendor_name text,
  reference_no text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'pending_approval'::text, 'approved'::text, 'paid'::text, 'rejected'::text, 'cancelled'::text])),
  created_by_user_id uuid,
  reviewed_by_user_id uuid,
  reviewed_at timestamp with time zone,
  approved_by_user_id uuid,
  approved_at timestamp with time zone,
  rejected_by_user_id uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  proof_uploaded boolean NOT NULL DEFAULT false,
  journal_entry_id uuid,
  is_large_transaction boolean NOT NULL DEFAULT false,
  large_transaction_threshold numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT payment_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT payment_requests_fund_id_fkey FOREIGN KEY (fund_id) REFERENCES public.funds(id),
  CONSTRAINT payment_requests_expense_account_id_fkey FOREIGN KEY (expense_account_id) REFERENCES public.accounts(id),
  CONSTRAINT payment_requests_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id),
  CONSTRAINT payment_requests_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT payment_requests_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT payment_requests_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES public.users(id),
  CONSTRAINT payment_requests_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES public.users(id),
  CONSTRAINT payment_requests_rejected_by_user_id_fkey FOREIGN KEY (rejected_by_user_id) REFERENCES public.users(id),
  CONSTRAINT payment_requests_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id)
);
CREATE TABLE public.payment_webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  gateway text NOT NULL,
  event_id text NOT NULL,
  donation_transaction_id uuid,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  payload jsonb NOT NULL,
  headers jsonb,
  signature_valid boolean NOT NULL DEFAULT false,
  processed boolean NOT NULL DEFAULT false,
  processed_at timestamp with time zone,
  processing_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT payment_webhook_events_donation_transaction_id_fkey FOREIGN KEY (donation_transaction_id) REFERENCES public.donation_transactions(id)
);
CREATE TABLE public.platform_user_roles (
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT platform_user_roles_pkey PRIMARY KEY (user_id, role),
  CONSTRAINT platform_user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.project_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  project_id uuid NOT NULL,
  title text NOT NULL,
  report_body jsonb NOT NULL DEFAULT '{}'::jsonb,
  report_date date,
  submission_status text NOT NULL DEFAULT 'draft'::text CHECK (submission_status = ANY (ARRAY['draft'::text, 'submitted'::text])),
  verification_status text NOT NULL DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'changes_requested'::text, 'verified'::text, 'rejected'::text])),
  submitted_at timestamp with time zone,
  verified_at timestamp with time zone,
  verified_by_user_id uuid,
  reviewer_comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_reports_pkey PRIMARY KEY (id),
  CONSTRAINT project_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT project_reports_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_reports_verified_by_user_id_fkey FOREIGN KEY (verified_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  title text NOT NULL,
  objective text NOT NULL,
  description text,
  location_text text,
  start_date date,
  end_date date,
  budget_amount numeric,
  currency text NOT NULL DEFAULT 'MYR'::text,
  beneficiary_summary text,
  kpi_targets jsonb,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'completed'::text, 'archived'::text])),
  is_public boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.scholar_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  author_user_id uuid NOT NULL,
  note_body text NOT NULL,
  is_publishable boolean NOT NULL DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scholar_notes_pkey PRIMARY KEY (id),
  CONSTRAINT scholar_notes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT scholar_notes_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.trust_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['report_verified'::text, 'financial_submitted'::text, 'financial_verified'::text, 'certification_updated'::text, 'donation_confirmed'::text, 'complaint_logged'::text, 'complaint_resolved'::text, 'report_overdue_flagged'::text, 'report_overdue_cleared'::text, 'manual_recalc'::text, 'fi_period_closed'::text, 'fi_period_closed_late'::text, 'fi_bank_reconciled'::text, 'fi_bank_discrepancy'::text, 'fi_bank_unreconciled_30d'::text, 'fi_fund_segregated'::text, 'fi_fund_restriction_violated'::text, 'fi_fund_overspent'::text, 'fi_expense_with_receipt'::text, 'fi_expense_no_receipt'::text, 'fi_large_donation_recorded'::text, 'fi_bank_account_linked'::text, 'gov_payment_dual_approved'::text, 'gov_payment_self_approved'::text, 'gov_approval_rejected'::text, 'gov_approval_overdue'::text, 'gov_role_segregation_verified'::text, 'gov_policy_uploaded'::text, 'gov_policy_overdue'::text, 'gov_board_meeting_recorded'::text, 'gov_board_meeting_overdue'::text, 'gov_conflict_declared'::text, 'gov_case_approved'::text, 'gov_case_approved_conditional'::text, 'gov_case_improvement_required'::text, 'gov_case_rejected'::text, 'gov_case_expired'::text, 'com_audit_submitted'::text, 'com_audit_unqualified'::text, 'com_audit_qualified'::text, 'com_audit_overdue'::text, 'com_regulatory_filed'::text, 'com_regulatory_overdue'::text, 'com_shariah_review_completed'::text, 'com_shariah_noncompliance'::text, 'trn_financial_published'::text, 'trn_donor_report_published'::text, 'trn_disclosure_overdue'::text, 'trn_annual_report_published'::text, 'trn_complaint_received'::text, 'trn_complaint_resolved'::text, 'trust_snapshot_published'::text, 'imp_program_completed'::text, 'imp_program_delayed'::text, 'imp_beneficiary_verified'::text, 'imp_impact_report_verified'::text, 'sys_audit_log_tampered'::text, 'sys_suspicious_login'::text, 'score_decay_applied'::text])),
  event_ref_table text,
  event_ref_id uuid,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  actor_user_id uuid,
  source text NOT NULL DEFAULT 'system'::text CHECK (source = ANY (ARRAY['user'::text, 'reviewer'::text, 'webhook'::text, 'system'::text])),
  idempotency_key text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  pillar text CHECK (pillar = ANY (ARRAY['financial_integrity'::text, 'governance'::text, 'compliance'::text, 'transparency'::text, 'impact'::text, 'system'::text])),
  score_delta numeric DEFAULT 0,
  CONSTRAINT trust_events_pkey PRIMARY KEY (id),
  CONSTRAINT trust_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT trust_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_provider text NOT NULL DEFAULT 'supabase'::text,
  auth_provider_user_id text NOT NULL,
  email text NOT NULL UNIQUE,
  display_name text,
  platform_role text NOT NULL DEFAULT 'donor'::text CHECK (platform_role = ANY (ARRAY['donor'::text, 'reviewer'::text, 'scholar'::text, 'super_admin'::text])),
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);