// apps/org/app/api/members/invite/route.ts
// Sprint 25 — Send org member invitation
import { createClient }        from '@/lib/supabase/server';
import { createServiceClient } from '@/lib/supabase/service';
import { NextRequest, NextResponse } from 'next/server';
function relationOne<T>(value: unknown): T | null {
  if (Array.isArray(value)) {
    return (value[0] as T | undefined) ?? null;
  }
  return (value as T | null) ?? null;
}


export async function POST(request: NextRequest) {
  const supabase = await createClient();
  const service  = createServiceClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthenticated' }, { status: 401 });

  const { data: platformUser } = await supabase
    .from('users').select('id').eq('auth_provider_user_id', user.id).single();
  if (!platformUser) return NextResponse.json({ error: 'Not found' }, { status: 404 });

  const { orgId, email, role } = await request.json();

  // Must be org_admin to invite
  const { data: membership } = await service
    .from('org_members').select('org_role')
    .eq('organization_id', orgId).eq('user_id', platformUser.id)
    .eq('status', 'active').single();
  if (!membership || membership.org_role !== 'org_admin')
    return NextResponse.json({ error: 'Admin role required to invite members' }, { status: 403 });

  // Validate role
  if (!['org_admin','org_manager','org_viewer'].includes(role))
    return NextResponse.json({ error: 'Invalid role' }, { status: 400 });

  // Check no existing pending invite for this email + org
  const { data: existing } = await service
    .from('org_invitations')
    .select('id').eq('organization_id', orgId)
    .eq('invited_email', email.toLowerCase()).eq('status', 'pending').maybeSingle();
  if (existing) return NextResponse.json({ error: 'A pending invitation already exists for this email.' }, { status: 400 });

  // Check not already a member
  const { data: existingMember } = await service
    .from('org_members')
    .select('id, users(email)')
    .eq('organization_id', orgId).eq('status', 'active').limit(50);
  const alreadyMember = (existingMember ?? []).some(
    (m) => relationOne<{ email: string }>(m.users)?.email?.toLowerCase() === email.toLowerCase()
  );
  if (alreadyMember) return NextResponse.json({ error: 'This person is already a member of your organisation.' }, { status: 400 });

  // Create invitation — token generated by DB default
  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
  const { data: inv, error: invError } = await service
    .from('org_invitations')
    .insert({
      organization_id:    orgId,
      invited_email:      email.toLowerCase(),
      org_role:           role,
      invited_by_user_id: platformUser.id,
      status:             'pending',
      expires_at:         expiresAt,
    })
    .select('id, token').single();

  if (invError) return NextResponse.json({ error: invError.message }, { status: 500 });

  // TODO: Send invitation email via Supabase Edge Function send-invite-email
  // For now the invitation token is in the DB and can be used via the invite accept flow
  // The edge function already exists: supabase/functions/send-invite-email/

  return NextResponse.json({ success: true, invitationId: inv.id });
}
